### ISSUE TITLE
Add timeout

### ISSUE THREAD

**Issue by guyzmo** [hypertrack/hypertrack-ruby#1]
cf [that method](https://github.com/hypertrack/hypertrack-ruby/blob/97124694f0367a19536de2da75834c7eb21d42a1/lib/hypertrack/api_client.rb#L71)

would it be possible to add a short timeout period, like:

```ruby
conn = Net::HTTP.new(host, port)
conn.read_timeout = 10
```

and eventually make it configurable at init time of rails (or using an env variable?).

I've just been stung by this, all the requests are timeouting at 1min, making my app unusable.

**Comment by nileshtrivedi** [comment]
Fixed by merging https://github.com/hypertrack/hypertrack-ruby/pull/2
